import { MJParamConfig } from "./types"

const v6 = {
  no: { type: String, default: '', short: '--no' },
  stop: { type: Number, default: 100, short: '--stop' },
  chaos: { type: Number, default: 0, short: '--c' },
  ar: { type: String, default: '1:1', short: '--ar' },
  quality: { type: Number, default: 1, short: '--q' },
  style: { type: String, default: 'standart', short: '--style' },
  raw: { type: Boolean, default: false, short: '--raw' },
  cref: { type: String, default: '', short: '--cref' },
  profile: { type: String, default: '', short: '--p' },
  stylize: { type: Number, default: 100, short: '--s' },
  weird: { type: Number, default: 0, short: '--w' },
  version: { type: String, default: '7', short: '--v' },
  repeat: { type: Number, default: 1, short: '--r' },
  seed: { type: Number, default: 0, short: '--seed' },
  sref: { type: String, default: '', short: '--sref' },
  tile: { type: Boolean, default: false, short: '--tile' },
  video: { type: Boolean, default: false, short: '--video' },
  fast: { type: Boolean, default: false, short: '--fast' },
  iw: { type: Number, default: 0.25, short: '--iw' },
  relax: { type: Boolean, default: false, short: '--relax' },
  turbo: { type: Boolean, default: false, short: '--turbo' },
  niji: { type: String, default: '6', short: '--niji' },
  stealth: { type: Boolean, default: false, short: '--stealth' },
  public: { type: Boolean, default: false, short: '--public' },
}

const params: Record<string, MJParamConfig> = {
  '7': {
    no: { type: String, default: '', short: '--no' },
    stop: { type: Number, default: 100, short: '--stop' },
    chaos: { type: Number, default: 0, short: '--c' },
    ar: { type: String, default: '1:1', short: '--ar' },
    style: { type: String, default: 'standart', short: '--style' },
    raw: { type: Boolean, default: false, short: '--raw' },
    cref: { type: String, default: '', short: '--cref' },
    profile: { type: String, default: '', short: '--p' },
    stylize: { type: Number, default: 100, short: '--s' },
    weird: { type: Number, default: 0, short: '--w' },
    version: { type: String, default: '6.1', short: '--v' },
    repeat: { type: Number, default: 1, short: '--r' },
    seed: { type: Number, default: 0, short: '--seed' },
    sref: { type: String, default: '', short: '--sref' },
    tile: { type: Boolean, default: false, short: '--tile' },
    video: { type: Boolean, default: false, short: '--video' },
    fast: { type: Boolean, default: false, short: '--fast' },
    iw: { type: Number, default: 0.25, short: '--iw' },
    relax: { type: Boolean, default: false, short: '--relax' },
    turbo: { type: Boolean, default: false, short: '--turbo' },
    niji: { type: String, default: '6', short: '--niji' },
    stealth: { type: Boolean, default: false, short: '--stealth' },
    public: { type: Boolean, default: false, short: '--public' },
    exp: { type: Number, default: 0, short: '--exp' },
    oref: { type: String, default: '', short: '--oref' },
    ow: { type: Number, default: 0, short: '--ow' },
  },
  '6.1': v6,
  '6': v6,
};
export default params